# Generated by Django 3.0.8 on 2020-08-08 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0002_comments_following_posts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posts',
            name='user',
        ),
    ]
