# Generated by Django 3.1.2 on 2020-11-28 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0007_posts_likes'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='todo_likes',
            constraint=models.UniqueConstraint(fields=('todo', 'user'), name='unique_like'),
        ),
    ]
