# Generated by Django 3.1.2 on 2020-11-28 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0008_auto_20201128_0537'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='following',
            constraint=models.UniqueConstraint(fields=('user', 'people'), name='unique_following'),
        ),
    ]
